# Header
menu:
  - {name: Home, path: /, class: fa-home, layout: 2}
  - {name: About, path: /about, class: fa-user, layout: 2}
  - {name: Archives, path: /archives, class: fa-archive, layout: 2}
#  - {name: Tags, path: /tags, class: fa-tags, layout: 2}
#  - {name: Gallery, path: /gallery, class: fa-camera, layout: 2}
#  - {name: Works, path: /works, class: fa-trophy, layout: 2}

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: top
widgets:
#- timeanddate
- qrcode
- category
- recent_posts
- tagcloud
- links
- counter
- reward
- ukagaka

# Miscellaneous
google_analytics:
favicon:
twitter:
google_plus: 114761524022260759157
fb_admins:
fb_app_id:

# Google sitemap
google_siteVerification:
  id: 5mRgj8NanEMpGZuNfHNJNmH90RgNlrnJXsFlTaKD6Gs

# Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.

## social
facebook_url: https://www.facebook.com/100005630052910
github_url: https://github.com/liangzhenduo0608
google_plus_url: https://plus.google.com/114761524022260759157
twitter_url: https://twitter.com/liangzhenduo
linkedin_url: http://www.linkedin.com/in/zhenduo-liang-795110131
instagram_url: https://www.instagram.com/liangzhenduo
weibo_url: http://weibo.com/378950608
renren_url: http://www.renren.com/357959793
qzone_url: http://user.qzone.qq.com/825875484
mail_url: mailto:liangzhenduo0608@hotmail.com
